Updated MISP dockerfiles for newer docker version

diff --git a/thehive-cortex-misp-wazuh/core/Dockerfile b/thehive-cortex-misp-wazuh/core/Dockerfile
--- a/thehive-cortex-misp-wazuh/core/Dockerfile
+++ b/thehive-cortex-misp-wazuh/core/Dockerfile
@@ -102,62 +102,56 @@ FROM php-base AS python-build
         && apt-get autoremove -y && apt-get clean -y && rm -rf /var/lib/apt/lists/*
 
     # Download MISP using git in the /var/www/ directory. Remove unnecessary items.
-    RUN <<-EOF
-        if [ ! -z "${CORE_COMMIT}" ]; then
-            git clone https://github.com/MISP/MISP.git /var/www/MISP && cd /var/www/MISP && git checkout "${CORE_COMMIT}"
-        else
-            git clone --branch "${CORE_TAG}" --depth 1 https://github.com/MISP/MISP.git /var/www/MISP
-        fi
-        cd /var/www/MISP || exit; git submodule update --init --recursive .
-EOF
+    RUN bash -c 'if [ ! -z "${CORE_COMMIT}" ]; then \
+        git clone https://github.com/MISP/MISP.git /var/www/MISP && cd /var/www/MISP && git checkout "${CORE_COMMIT}"; \
+    else \
+        git clone --branch "${CORE_TAG}" --depth 1 https://github.com/MISP/MISP.git /var/www/MISP; \
+    fi; \
+    cd /var/www/MISP || exit; git submodule update --init --recursive .'
 
-    RUN <<-EOF
-        mkdir /wheels
 
-        # Add additional dependencies (container specific)
-        # The "set" line contains the list of modules we want to ensure are present.
-        # PYPI_MODULE_NAME_VERSION env vars can be set to specify the version desired,
-        # e.g. PYPI_SURICATA_VERSION="==2.0" to specify exactly version 2.0 for the suricata package
-        #
-        # 1. Check for presence of each module in requirements.txt
-        # 2. If missing, add it (with optional version from env (defaults to empty string))
-        # 3. If present, replace with our specified version if it exists, otherwise leave
-        #    the upstream version alone.
-        set -- "redis" "lief" "pydeep2" "python-magic" "misp-lib-stix2" "maec" "mixbox" "cybox" "pymisp" "misp-stix"
-        for mod in "$@"; do
-            mod_version_var=$(echo "PYPI_${mod}_VERSION" | tr '[:lower:]' '[:upper:]' | tr '-' '_')
-            mod_version=$(eval "echo \"\$$mod_version_var\"")
-            grep -q ${mod} /var/www/MISP/requirements.txt
-            exists=$?
-            if [ "${exists}" -eq "1" ]; then
-                echo "Adding missing module ${mod} with version '${mod_version}'"
-                echo ${mod}${mod_version} >> /var/www/MISP/requirements.txt
-            else
-                if [ "$(echo ${mod_version} | wc -m)" -gt 1 ]; then
-                    echo "Overwriting existing module ${mod}, version '${mod_version}'"
-                    sed -i "/${mod}/s/.*/${mod}${mod_version}/" /var/www/MISP/requirements.txt
-                else
-                    echo "Skipping overwriting ${mod} due to missing version variable"
-                fi
-            fi
-        done;
 
-        pip wheel --no-cache-dir -w /wheels/ -r /var/www/MISP/requirements.txt
-
-        # Remove files we do not care for
-        find /var/www/MISP/INSTALL/* ! -name 'MYSQL.sql' -type f -exec rm {} +
-        find /var/www/MISP/INSTALL/* ! -name 'MYSQL.sql' -type l -exec rm {} +
-        # Remove most files in .git - we do not use git functionality in docker
-        find /var/www/MISP/.git/* ! -name HEAD -exec rm -rf {} +
-        # Remove libraries submodules
-        rm -r /var/www/MISP/PyMISP
-        rm -r /var/www/MISP/app/files/scripts/cti-python-stix2
-        rm -r /var/www/MISP/app/files/scripts/misp-stix
-        rm -r /var/www/MISP/app/files/scripts/mixbox
-        rm -r /var/www/MISP/app/files/scripts/python-cybox
-        rm -r /var/www/MISP/app/files/scripts/python-maec
-        rm -r /var/www/MISP/app/files/scripts/python-stix
-EOF
+    RUN bash -c 'mkdir /wheels; \
+        # Add additional dependencies (container specific) \
+        # The "set" line contains the list of modules we want to ensure are present. \
+        # PYPI_MODULE_NAME_VERSION env vars can be set to specify the version desired, \
+        # e.g. PYPI_SURICATA_VERSION="==2.0" to specify exactly version 2.0 for the suricata package; \
+        # \
+        # 1. Check for presence of each module in requirements.txt \
+        # 2. If missing, add it (with optional version from env (defaults to empty string)) \
+        # 3. If present, replace with our specified version if it exists, otherwise leave \
+        set -- "redis" "lief" "pydeep2" "python-magic" "misp-lib-stix2" "maec" "mixbox" "cybox" "pymisp" "misp-stix"; \
+        for mod in "$@"; do \
+            mod_version_var=$(echo "PYPI_${mod}_VERSION" | tr '[:lower:]' '[:upper:]' | tr '-' '_'); \
+            mod_version=$(eval "echo \"\$$mod_version_var\""); \
+            grep -q ${mod} /var/www/MISP/requirements.txt; \
+            exists=$?; \
+            if [ "${exists}" -eq "1" ]; then \
+                echo "Adding missing module ${mod} with version '${mod_version}'"; \
+                echo ${mod}${mod_version} >> /var/www/MISP/requirements.txt; \
+            else \
+                if [ "$(echo ${mod_version} | wc -m)" -gt 1 ]; then \
+                    echo "Overwriting existing module ${mod}, version '${mod_version}'"; \
+                    sed -i "/${mod}/s/.*/${mod}${mod_version}/" /var/www/MISP/requirements.txt; \
+                else \
+                    echo "Skipping overwriting ${mod} due to missing version variable"; \
+                fi; \
+            fi; \
+        done; \
+        pip wheel --no-cache-dir -w /wheels/ -r /var/www/MISP/requirements.txt; \
+        # Remove files we do not care for \
+        find /var/www/MISP/INSTALL/* ! -name 'MYSQL.sql' -type f -exec rm {} +; \
+        find /var/www/MISP/INSTALL/* ! -name 'MYSQL.sql' -type l -exec rm {} +; \
+        # Remove most files in .git - we do not use git functionality in docker \
+        find /var/www/MISP/.git/* ! -name HEAD -exec rm -rf {} +; \
+        # Remove libraries submodules \
+        rm -r /var/www/MISP/PyMISP; \
+        rm -r /var/www/MISP/app/files/scripts/cti-python-stix2; \
+        rm -r /var/www/MISP/app/files/scripts/misp-stix; \
+        rm -r /var/www/MISP/app/files/scripts/mixbox; \
+        rm -r /var/www/MISP/app/files/scripts/python-cybox; \
+        rm -r /var/www/MISP/app/files/scripts/python-maec; \
+        rm -r /var/www/MISP/app/files/scripts/python-stix'
 
 
 FROM php-base
@@ -230,16 +224,15 @@ FROM php-base
     RUN pip uninstall -y setuptools pip
 
     # Gather these in one layer, only act on actual directories under /etc/php/
-    RUN <<-EOF
-        set -- "ssdeep" "rdkafka" "brotli" "simdjson" "zstd"
-        for mod in "$@"; do
-            for dir in /etc/php/*/; do
-                echo "extension=${mod}.so" > "${dir}mods-available/${mod}.ini"
-            done;
-            phpenmod "${mod}"
-        done;
-        phpenmod redis
-EOF
+    RUN bash -c 'set -- "ssdeep" "rdkafka" "brotli" "simdjson" "zstd"; \
+        for mod in "$@"; do \
+            for dir in /etc/php/*/; do \
+                echo "extension=${mod}.so" > "${dir}mods-available/${mod}.ini"; \
+            done; \
+            phpenmod "${mod}"; \
+        done; \
+        phpenmod redis'
+
 
     # nginx
     RUN rm /etc/nginx/sites-enabled/*; mkdir -p /run/php /etc/nginx/certs
@@ -251,15 +244,13 @@ EOF
     #   2) Files executable and read only, because of some rogue scripts like 'cake'
     #   3) Directories writable, because sometimes MISP add new files
 
-    RUN <<-EOF
-        cp -R /var/www/MISP/app/files /var/www/MISP/app/files.dist
-        cp -R /var/www/MISP/app/Config /var/www/MISP/app/Config.dist
-        find /var/www/MISP \( ! -user www-data -or ! -group www-data \) -exec chown www-data:www-data '{}' +;
-        find /var/www/MISP -not -perm 550 -type f -exec chmod 0550 '{}' +;
-        find /var/www/MISP -not -perm 770 -type d -exec chmod 0770 '{}' +;
-        # Diagnostics wants this file to be present and writable even if we do not use git in docker land
-        touch /var/www/MISP/.git/ORIG_HEAD && chmod 0600 /var/www/MISP/.git/ORIG_HEAD && chown www-data:www-data /var/www/MISP/.git/ORIG_HEAD
-EOF
+    RUN bash -c 'cp -R /var/www/MISP/app/files /var/www/MISP/app/files.dist; \
+        cp -R /var/www/MISP/app/Config /var/www/MISP/app/Config.dist; \
+        find /var/www/MISP \( ! -user www-data -or ! -group www-data \) -exec chown www-data:www-data "{}" +; \
+        find /var/www/MISP -not -perm 550 -type f -exec chmod 0550 "{}" +; \
+        find /var/www/MISP -not -perm 770 -type d -exec chmod 0770 "{}" +; \
+        touch /var/www/MISP/.git/ORIG_HEAD && chmod 0600 /var/www/MISP/.git/ORIG_HEAD && chown www-data:www-data /var/www/MISP/.git/ORIG_HEAD'
+
 
     # Copy all our image specific files to appropriate locations
     COPY files/ /
